const UPGRADE_REQUESTED = 'UPGRADE_REQUESTED'
const UPGRADE_REJECTED = 'UPGRADE_REJECTED'
const UPGRADE_SUCCESS = 'UPGRADE_SUCCESS'
const UPGRADE_FAILED = 'UPGRADE_FAILED'

const ERROR_MESSAGE = 'ERROR_MESSAGE'
const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE'

const SET_MENU = 'SET_MENU'

const SET_VILLAGE = 'SET_VILLAGE'

module.exports = {
    UPGRADE_REQUESTED,
    UPGRADE_REJECTED,
    UPGRADE_SUCCESS,
    UPGRADE_FAILED,

    ERROR_MESSAGE,
    SUCCESS_MESSAGE,

    SET_MENU,

    SET_VILLAGE,
}
