const UPGRADE_REQUESTED = 'UPGRADE_REQUESTED'
const UPGRADE_REJECTED = 'UPGRADE_REJECTED'
const UPGRADE_SUCCESS = 'UPGRADE_SUCCESS'
const UPGRADE_FAILED = 'UPGRADE_FAILED'

const ERROR_MESSAGE = 'ERROR_MESSAGE'
const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE'

const SET_MENU = 'SET_MENU'

const SET_VILLAGE = 'SET_VILLAGE'
const SET_FIELD = 'SET_FIELD'

const LOAD_DATA_REQUESTED = 'LOAD_DATA_REQUESTED'
const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS'
const LOAD_DATA_FAILED = 'LOAD_DATA_FAILED'

const SET_RESOURCES = 'SET_RESOURCES'

module.exports = {
    UPGRADE_REQUESTED,
    UPGRADE_REJECTED,
    UPGRADE_SUCCESS,
    UPGRADE_FAILED,

    ERROR_MESSAGE,
    SUCCESS_MESSAGE,

    SET_MENU,

    SET_VILLAGE,
    SET_FIELD,

    LOAD_DATA_REQUESTED,
    LOAD_DATA_SUCCESS,
    LOAD_DATA_FAILED,

    SET_RESOURCES,
}
